services:
  website:
    build:
      context: website
    ports:
      - 5173:5173
    develop:
      watch:
        - path: ./website
          action: sync
          target: /app
          ignore:
            - node_modules
  server:
    build:
      context: .
      dockerfile: dockerfile
      # target: final
    ports:
      - 3000:3000
    environment:
      - ENV=development
      - OTEL_LOGS_EXPORTER=none
      - LOG_TO_STDOUT=true
      - DATABASE_URL=postgres://postgres:example@db:5432/postgres
      - REDIS_URL=redis://rdb:6379/0
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://prometheus:9090/api/v1/otlp/v1/metrics
    depends_on:
      db:
        condition: service_started
      rdb:
        condition: service_started
    links:
      - db
      - rdb
    volumes:
      - ./:/app
  db:
    image: postgres
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=example
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  rdb:
    image: redis
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
  # otel-collector:
  #   image: otel/opentelemetry-collector-contrib
  #   volumes:
  #     - ./collector/config.yaml:/etc/otelcol-contrib/config.yaml
  #   ports:
  #     - 1888:1888 # pprof extension
  #     - 8888:8888 # Prometheus metrics exposed by the Collector
  #     - 8889:8889 # Prometheus exporter metrics
  #     - 13133:13133 # health_check extension
  #     - 4317:4317 # OTLP gRPC receiver
  #     - 4318:4318 # OTLP http receiver
  #     - 55679:55679 # zpages extension
  loki:
    image: grafana/loki
    ports:
      - 3100:3100
    volumes:
      - loki-data:/loki
      - ./loki/loki.yaml:/etc/loki/loki.yaml
    attach: false
  prometheus:
    image: prom/prometheus
    command:
      - "--web.enable-otlp-receiver"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus:/etc/prometheus/
    attach: false
  grafana:
    image: grafana/grafana
    ports:
      - 9000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning/datasources/
    attach: false

volumes:
  db-data:
  redis-data:
  prometheus-data:
  grafana-data:
  loki-data:
