apiVersion: 1

datasources:
  - name: Main
    type: prometheus
    uid: prom
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - name: trace_id
          datasourceUid: tempo
          urlDisplayLabel: "View Trace"
          # https://github.com/grafana/loki/issues/9209#issuecomment-1882710470
          matcherType: label
          matcherRegex: trace_id
          url: "$${__value.raw}"
        # - name: span_id
        #   datasourceUid: tempo
        #   urlDisplayLabel: "View Span"
        #   matcherType: label
        #   matcherRegex: span_id
        #   url: "$${__value.raw}"
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "-5m"
        spanEndTimeShift: "5m"
        filterByTraceID: true
        filterBySpanID: true
        tags:
          [
            { key: "service.name", value: "service_name" },
            { key: "service.namespace", value: "service_namespace" },
            { key: "service.instance.id", value: "service_instance_id" },
          ]
        customQuery: true
        query: '{$${__tags}} | trace_id="$${__span.traceId}"'
