FROM node:24.4-alpine

WORKDIR /app

COPY package.json .
COPY yarn.lock .
COPY .yarnrc.yml .

RUN corepack enable
RUN yarn set version berry
RUN yarn install --immutable

COPY . .

EXPOSE 5173

CMD ["yarn", "dev"]
