# Learn more about the OpenTelemetry Collector via
# https://opentelemetry.io/docs/collector/

receivers:
  otlp:
    protocols:
      # grpc:
      #   endpoint: 0.0.0.0:4317
      #   tls:
      #     cert_file: cert.pem
      #     key_file: cert-key.pem
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: default
    # endpoint: prometheus:9090
    # endpoint: otelcol:4317
    # namespace: default

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]
    # logs:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [prometheus]
