# Learn more about the OpenTelemetry Collector via
# https://opentelemetry.io/docs/collector/

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 10s
          static_configs:
            - targets: ["0.0.0.0:8888"]
  hostmetrics:
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      process:
        mute_process_user_error: true
      processes:
      paging:

processors:
  memory_limiter:
    limit_mib: 1365 # 75% of maximum memory up to 1G
    spike_limit_mib: 256 # 25% of limit up to 1G
    check_interval: 5s
  batch:

exporters:
  debug:
    verbosity: detailed
  otlphttp/metrics:
    endpoint: prometheus:9090
    metrics_endpoint: http://prometheus:9090/api/v1/otlp/v1/metrics
    tls:
      insecure: true
  otlphttp/logs:
    endpoint: http://loki:3100/otlp
    logs_endpoint: http://loki:3100/otlp/v1/logs
    tls:
      insecure: true
  otlphttp/traces:
    endpoint: http://tempo/v1/traces
    traces_endpoint: http://tempo:4318/v1/traces
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    metrics:
      receivers: [otlp, prometheus, hostmetrics]
      processors: [memory_limiter, batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/logs]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/traces]
